### ISSUE TITLE
Bug report via Twitter

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/BeTrains-for-Android#6] opened 2015-03-08 17:44 UTC
https://twitter.com/Cimm/status/573759551167664128

**Comment by cimm** [comment] 2015-03-09 12:45
Deleting the `android/data/betrains` folder fixes the can-not-open-the-app issue but... I can reproduce the problem.

Open the app and search for a trip, the Beligian flag loading bar scrolls and scrolls... but the result screen is empty. Looks like the app is searching for train connections but I have the feeling it's not doing anything. Left it on for a few minutes but when I click the hamburger menu at this stage the app crashes and I'll have to delete the data directory again.

**Comment by cimm** [comment] 2015-03-09 12:50
Aha, I removed the data directory and app from my phone. Went to the Play store and installed the app. Tried searching for trip and... it works! So, the issue is related with the version on [F-Droid](https://f-droid.org/repository/browse/?fdfilter=betrains&fdid=tof.cv.mpp). Is this the wrong version maybe?

**Comment by ChristopheVersieux** [comment] 2015-03-09 12:50
Just a question, is there something in the text file inside this folder? 
Would be easier if you could test the Play Store version and see if the problem happens.. Just in case, I will share an apk.
I suspect the Fdroid builds to have an issue, I need to investigate!

**Comment by cimm** [comment] 2015-03-09 12:55
Back to the F-Droid version. It creates the `android/data/betrains` folder with a `connections.txt` file when starting a search. The txt file looks like a JSON file:


```


{"version":"1.1","timestamp":"1425905521","connection":[{"id":"0","departure":{"delay":"60","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425905520","vehicle":"BE.NMBS.L4862","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Tournai"},"@id":"http://irail.be/stations/NMBS/008881000/departures/2015030913523bb1ef745b11bfbeb8a118a1def6b905"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425908160","vehicle":"BE.NMBS.L4862","platform":"2","platforminfo":{"name":"2","normal":"1"},"direction":{"name":"Tournai"}},"duration":"2640"},{"id":"1","departure":{"delay":"0","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425908700","vehicle":"BE.NMBS.IC935","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Tournai"},"@id":"http://irail.be/stations/NMBS/008881000/departures/201503091445be59507af076320ebf83dddf47145497"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425910500","vehicle":"BE.NMBS.IC935","platform":"2","platforminfo":{"name":"2","normal":"1"},"direction":{"name":"Tournai"}},"duration":"1800"},{"id":"2","departure":{"delay":"0","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425909120","vehicle":"BE.NMBS.L4863","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Moeskroen / Mouscron"},"@id":"http://irail.be/stations/NMBS/008881000/departures/2015030914525aefe596cd807002ef05fe99d4da9b92"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425911760","vehicle":"BE.NMBS.L4863","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Moeskroen / Mouscron"}},"duration":"2640"},{"id":"3","departure":{"delay":"0","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425912300","vehicle":"BE.NMBS.IC936","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Tournai"},"@id":"http://irail.be/stations/NMBS/008881000/departures/201503091545bb7d7d84900e12284c2d230430b33537"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425914100","vehicle":"BE.NMBS.IC936","platform":"1","platforminfo":{"name":"1","normal":"1"},"direction":{"name":"Tournai"}},"duration":"1800"},{"id":"4","departure":{"delay":"0","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425912720","vehicle":"BE.NMBS.L4864","platform":"4","platforminfo":{"name":"4","normal":"1"},"direction":{"name":"Moeskroen / Mouscron"},"@id":"http://irail.be/stations/NMBS/008881000/departures/201503091552a295ded79a77d69fd30ebf65b6102a04"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425915360","vehicle":"BE.NMBS.L4864","platform":"2","platforminfo":{"name":"2","normal":"1"},"direction":{"name":"Moeskroen / Mouscron"}},"duration":"2640"},{"id":"5","departure":{"delay":"0","station":"Mons","stationinfo":{"id":"BE.NMBS.008881000","locationX":"3.942542","locationY":"50.453854","@id":"http://irail.be/stations/NMBS/008881000","name":"Mons","standardname":"Mons"},"time":"1425914340","vehicle":"BE.NMBS.P8861","platform":"5","platforminfo":{"name":"5","normal":"1"},"direction":{"name":"Tournai"},"@id":"http://irail.be/stations/NMBS/008881000/departures/201503091619a96c8fa02eba36fa5071753266159d16"},"arrival":{"delay":"0","station":"Tournai","stationinfo":{"id":"BE.NMBS.008885001","locationX":"3.396942","locationY":"50.613134","@id":"http://irail.be/stations/NMBS/008885001","name":"Tournai","standardname":"Tournai"},"time":"1425917460","vehicle":"BE.NMBS.P8861","platform":"3","platforminfo":{"name":"3","normal":"1"},"direction":{"name":"Tournai"}},"duration":"3120"}]}

```

**Comment by ChristopheVersieux** [comment] 2015-10-27 07:29
Is this issue fixed with the updates in the meanwhile?

**Comment by cimm** [comment] 2015-10-29 12:11
I no longer have an Andorid phone, so difficult to say. Sorry.

**Closed** 2015-11-06 10:04 UTC
